name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with: 
          versionSpec: '5.x'
      - name: determine version
        uses: gittools/actions/gitversion/execute@v0.10.2
        id: gitversion
      - name: Get the GitVersion output
        run: echo "The GitVersion is ${{ steps.gitversion.outputs.semVer }}"
      - name: release our repo
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.gitversion.outputs.semVer }}
          release_name: Release ${{ steps.gitversion.outputs.semVer }}
